name: Mirror to Gitee repo

on:
  push:
    branches:
      - master

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: Yikun/hub-mirror-action@v1.2
        with:
          src: github/dongwei1125
          dst: gitee/dongwei1125
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          static_list: 'blog'
          force_update: true
